#!/usr/bin/env bash
# script that Install nginx web server
# Nginx should be listening on port 80

sudo apt-get update -y
sudo apt-get install nginx -y
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
