#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Configure haproxy configuration file
server_config=\
"
frontend doretest
        bind *:80
        mode http
        default_backend web_servers
backend web_servers
        balance roundrobin
        server studentid-web-01 54.173.224.120:80 check
	server studentid-web-02 54.152.154.67:80 check
"
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg

# Restart the service
sudo service haproxy restart
