#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
# Where only the part of the name after the first dash is displayed.

list=$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done
