#!/usr/bin/env bash
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080

service apache2 stop
sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx restart
