#!/usr/bin/env bash
# Configure nginx to only nginx user anf listen to port 8080

service apache2 stop
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
